version: '2'

services:

  redis:
    image: redis:3.0

  django:
    build: .
    ports:
      - "8841:8841"
    env_file:
      - ./environment
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./cactus:/cactus
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    env_file:
      - ./environment