# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 20:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20170513_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Description')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Time')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
