# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_task_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.CharField(max_length=256, verbose_name='Teacher`s name'),
        ),
    ]
