# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_task_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='fire_status',
            field=models.IntegerField(default=3, verbose_name='Fire status (1-10)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='labs_passed',
            field=models.IntegerField(default=30, verbose_name='Percent of done tasks'),
        ),
        migrations.AddField(
            model_name='subject',
            name='lessons_visited',
            field=models.IntegerField(default=50, verbose_name='Percent of visited pairs'),
        ),
    ]
